import {
  db,
  productsTable,
  collectionsTable,
  type InsertProduct,
  type InsertCollection,
} from "@workspace/db";

const standardSizes = ["XS", "S", "M", "L", "XL"];

const standardSizeGuide = [
  { size: "XS", bust: '32"', waist: '24"', hips: '34"', length: '47"' },
  { size: "S", bust: '34"', waist: '26"', hips: '36"', length: '47"' },
  { size: "M", bust: '36"', waist: '28"', hips: '38"', length: '48"' },
  { size: "L", bust: '38"', waist: '30"', hips: '40"', length: '48"' },
  { size: "XL", bust: '40"', waist: '32"', hips: '42"', length: '49"' },
];

const careInstructions = [
  "Dry clean only",
  "Steam to remove wrinkles — do not iron directly",
  "Store on a padded hanger away from direct sunlight",
];

type Seed = Omit<InsertProduct, "createdAt"> & { popularity: number };

const products: Seed[] = [
  {
    slug: "sienna-silk-slip",
    name: "Sienna Silk Slip",
    tagline: "A weightless terracotta slip for warm evenings",
    description:
      "Cut from feather-light mulberry silk, the Sienna falls in liquid lines from a slim cowl neckline. The terracotta tone catches candlelight beautifully — equally at home at a summer rehearsal dinner or an early autumn opening.",
    price: "228.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Slip",
    collection: "evening",
    color: "Terracotta",
    colorHex: "#B5573A",
    sizes: standardSizes,
    images: ["/products/sienna-silk-slip.png"],
    material: "100% Mulberry Silk",
    isNew: true,
    isBestSeller: true,
    rating: "4.90",
    reviewCount: 128,
    stock: 18,
    details: [
      "Bias-cut from 19mm mulberry silk",
      "Adjustable spaghetti straps",
      "Cowl neckline, low scoop back",
      "Hidden side seam zipper",
      "Designed and sewn in Los Angeles",
    ],
    careInstructions,
    sizeGuide: standardSizeGuide,
    popularity: 980,
  },
  {
    slug: "amelie-linen-midi",
    name: "Amélie Linen Midi",
    tagline: "Soft cream linen with quiet puff sleeves",
    description:
      "The Amélie is everything we want a daytime dress to be: relaxed but considered, breezy but never shapeless. Tailored from washed Belgian linen with a softly gathered waist and tea-length skirt.",
    price: "198.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Midi",
    collection: "day",
    color: "Cream",
    colorHex: "#EFE3CC",
    sizes: standardSizes,
    images: ["/products/amelie-linen-midi.png"],
    material: "100% Washed Belgian Linen",
    isNew: true,
    isBestSeller: false,
    rating: "4.80",
    reviewCount: 64,
    stock: 24,
    details: [
      "Washed for a lived-in softness from day one",
      "Subtle puff sleeves with elasticated cuffs",
      "Side seam pockets",
      "Covered button placket at the back",
    ],
    careInstructions: [
      "Machine wash cold on a delicate cycle",
      "Lay flat to dry",
      "Warm iron, or wear the wrinkles — they suit her",
    ],
    sizeGuide: standardSizeGuide,
    popularity: 540,
  },
  {
    slug: "nocturne-velvet-gown",
    name: "Nocturne Velvet Gown",
    tagline: "Floor-sweeping burgundy velvet",
    description:
      "Cut from a deep, light-drinking burgundy velvet, the Nocturne is built for long, loud nights. A bias-cut skirt sweeps the floor; thin straps cross a low back.",
    price: "486.00",
    compareAtPrice: "560.00",
    currency: "USD",
    category: "Gown",
    collection: "evening",
    color: "Burgundy",
    colorHex: "#5C1A2B",
    sizes: standardSizes,
    images: ["/products/nocturne-velvet-gown.png"],
    material: "Silk-Blend Velvet",
    isNew: false,
    isBestSeller: true,
    rating: "4.95",
    reviewCount: 92,
    stock: 9,
    details: [
      "Hand-cut on the bias for fluid drape",
      "Crossed strap detail at the back",
      "Floor-grazing length — designed to be worn with a low heel",
      "Concealed side zip",
    ],
    careInstructions,
    sizeGuide: standardSizeGuide,
    popularity: 1200,
  },
  {
    slug: "meadow-cotton-sundress",
    name: "Meadow Sundress",
    tagline: "Sage cotton with hand-stitched embroidery",
    description:
      "Inspired by an old French nightdress found at a market in Arles. Light cotton voile, a softly squared neckline, and tiny embroidered florals along the bodice.",
    price: "168.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Sundress",
    collection: "resort",
    color: "Sage",
    colorHex: "#A4B493",
    sizes: standardSizes,
    images: ["/products/meadow-cotton-sundress.png"],
    material: "100% Cotton Voile",
    isNew: true,
    isBestSeller: false,
    rating: "4.70",
    reviewCount: 47,
    stock: 30,
    details: [
      "Hand-embroidered floral motif across the bodice",
      "Tiered skirt with a midi length",
      "Square neckline, smocked back panel",
      "Side seam pockets",
    ],
    careInstructions: [
      "Hand wash cold",
      "Lay flat to dry in shade",
      "Warm iron on the reverse",
    ],
    sizeGuide: standardSizeGuide,
    popularity: 420,
  },
  {
    slug: "aurelia-satin-bias",
    name: "Aurelia Satin Bias",
    tagline: "Champagne satin that catches every light",
    description:
      "An understated stunner. The Aurelia drapes in a true bias cut, with a delicate cowl that softens at the collarbone and a back that scoops just enough.",
    price: "298.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Slip",
    collection: "evening",
    color: "Champagne",
    colorHex: "#E6D2A8",
    sizes: standardSizes,
    images: ["/products/aurelia-satin-bias.png"],
    material: "Silk Satin",
    isNew: false,
    isBestSeller: true,
    rating: "4.85",
    reviewCount: 153,
    stock: 14,
    details: [
      "True bias cut for a fluid silhouette",
      "Cowl neckline with adjustable straps",
      "Low scoop back",
      "Hidden side seam zip",
    ],
    careInstructions,
    sizeGuide: standardSizeGuide,
    popularity: 1080,
  },
  {
    slug: "coquelicot-poppy-dress",
    name: "Coquelicot Cocktail",
    tagline: "Poppy red, structured shoulders, knee-length",
    description:
      "Named for the wild poppies that line the country roads of Provence. A deep, joyful red in stretch crepe, with sculpted shoulders and a clean A-line skirt.",
    price: "318.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Cocktail",
    collection: "evening",
    color: "Poppy",
    colorHex: "#C9302C",
    sizes: standardSizes,
    images: ["/products/coquelicot-poppy-dress.png"],
    material: "Stretch Crepe",
    isNew: false,
    isBestSeller: false,
    rating: "4.75",
    reviewCount: 38,
    stock: 16,
    details: [
      "Sculpted shoulder line",
      "Clean A-line skirt, knee-length",
      "Lined bodice for a clean finish",
      "Concealed back zip",
    ],
    careInstructions,
    sizeGuide: standardSizeGuide,
    popularity: 380,
  },
  {
    slug: "bryony-tea-dress",
    name: "Bryony Tea Dress",
    tagline: "Dusty rose floral, smocked bodice",
    description:
      "A sweet, romantic tea dress in dusty rose with a delicate floral print. Smocked across the bodice for an easy fit; tiered skirt for a little movement.",
    price: "182.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Tea",
    collection: "day",
    color: "Dusty Rose",
    colorHex: "#C99098",
    sizes: standardSizes,
    images: ["/products/bryony-tea-dress.png"],
    material: "Cotton Lawn",
    isNew: false,
    isBestSeller: false,
    rating: "4.65",
    reviewCount: 51,
    stock: 22,
    details: [
      "Smocked bodice with a soft square neckline",
      "Tiered tea-length skirt",
      "Short fluttered sleeves",
      "Pull-on style",
    ],
    careInstructions: [
      "Machine wash cold on delicate",
      "Hang to dry",
      "Cool iron on reverse",
    ],
    sizeGuide: standardSizeGuide,
    popularity: 320,
  },
  {
    slug: "isolde-bridal-gown",
    name: "Isolde Bridal Gown",
    tagline: "Modern silk crepe for the unhurried bride",
    description:
      "Quiet, confident, and entirely modern. The Isolde is cut from heavy silk crepe in a slim, columnar silhouette — no train, no fuss, just beautifully made.",
    price: "1480.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Gown",
    collection: "bridal",
    color: "Ivory",
    colorHex: "#F5EFE2",
    sizes: standardSizes,
    images: ["/products/isolde-bridal-gown.png"],
    material: "Heavy Silk Crepe",
    isNew: true,
    isBestSeller: false,
    rating: "4.95",
    reviewCount: 21,
    stock: 6,
    details: [
      "Slim columnar silhouette in heavy silk crepe",
      "Delicate spaghetti straps",
      "Low V-back with covered buttons",
      "Floor-length, no train",
      "Made to order, allow 8–10 weeks",
    ],
    careInstructions,
    sizeGuide: standardSizeGuide,
    popularity: 700,
  },
  {
    slug: "maren-poplin-shirtdress",
    name: "Maren Shirtdress",
    tagline: "Butter yellow poplin, belted at the waist",
    description:
      "A perfect Saturday dress. Crisp cotton poplin in a soft butter yellow, with a deep collar, mother-of-pearl buttons, and a self-tie belt.",
    price: "188.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Shirtdress",
    collection: "day",
    color: "Butter",
    colorHex: "#EFD9A2",
    sizes: standardSizes,
    images: ["/products/maren-poplin-shirtdress.png"],
    material: "Cotton Poplin",
    isNew: false,
    isBestSeller: false,
    rating: "4.70",
    reviewCount: 73,
    stock: 28,
    details: [
      "Mother-of-pearl buttons",
      "Self-tie belt at the waist",
      "Cuffed three-quarter sleeves",
      "Side seam pockets",
    ],
    careInstructions: [
      "Machine wash cold",
      "Tumble dry low or hang to dry",
      "Iron while slightly damp",
    ],
    sizeGuide: standardSizeGuide,
    popularity: 290,
  },
  {
    slug: "selene-black-mini",
    name: "Selene Mini",
    tagline: "Sleek black crepe, long sleeves",
    description:
      "The little black dress, considered. Long sleeves, a high neckline, and a gentle A-line that lands above the knee — built from a substantial stretch crepe.",
    price: "248.00",
    compareAtPrice: null,
    currency: "USD",
    category: "Mini",
    collection: "evening",
    color: "Black",
    colorHex: "#1A1A1A",
    sizes: standardSizes,
    images: ["/products/selene-black-mini.png"],
    material: "Stretch Crepe",
    isNew: false,
    isBestSeller: true,
    rating: "4.88",
    reviewCount: 201,
    stock: 19,
    details: [
      "High mock neckline",
      "Long fitted sleeves",
      "Gentle A-line silhouette",
      "Above-the-knee length",
    ],
    careInstructions,
    sizeGuide: standardSizeGuide,
    popularity: 1340,
  },
];

const collections = [
  {
    slug: "evening",
    name: "Evening",
    description:
      "Long velvets, liquid silks, and sculpted crepes for the nights worth remembering.",
    coverImage: "/products/nocturne-velvet-gown.png",
  },
  {
    slug: "day",
    name: "Day",
    description:
      "Soft linens and cotton lawns for sunlit afternoons, slow lunches, and the rest of it.",
    coverImage: "/products/amelie-linen-midi.png",
  },
  {
    slug: "bridal",
    name: "Bridal",
    description:
      "Quiet, modern silhouettes for brides who would rather be themselves.",
    coverImage: "/products/isolde-bridal-gown.png",
  },
  {
    slug: "resort",
    name: "Resort",
    description:
      "Hand-embroidered cottons and breezy voiles for places with a coastline.",
    coverImage: "/products/meadow-cotton-sundress.png",
  },
] satisfies InsertCollection[];

async function main() {
  await db.delete(productsTable);
  await db.delete(collectionsTable);

  await db.insert(collectionsTable).values(collections);
  await db.insert(productsTable).values(products);

  console.log(`Seeded ${products.length} products, ${collections.length} collections.`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
